"""Copy reusable archetype fragments into a video project.

Examples:
  py tools/archetype_scaffold.py list
  py tools/archetype_scaffold.py init --project learn/output/demo
  py tools/archetype_scaffold.py init --project learn/output/demo --archetypes spotlight,timeline,console
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
import re
import shutil
import sys

ROOT = Path(__file__).resolve().parent.parent
LIB = ROOT / "templates" / "archetypes"
MANIFEST_PATH = LIB / "manifest.json"


def load_manifest() -> dict:
    if not MANIFEST_PATH.exists():
        raise FileNotFoundError(f"manifest not found: {MANIFEST_PATH}")
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


def known_names(manifest: dict) -> list[str]:
    return [row["name"] for row in manifest.get("archetypes", [])]


def parse_selection(raw: str | None, available: list[str]) -> list[str]:
    if not raw:
        return available
    picked = [name.strip() for name in raw.split(",") if name.strip()]
    unknown = [name for name in picked if name not in available]
    if unknown:
        raise ValueError(
            "unknown archetype(s): "
            + ", ".join(unknown)
            + "\nknown: "
            + ", ".join(available)
        )
    # Keep user order while removing duplicates.
    deduped: list[str] = []
    seen: set[str] = set()
    for name in picked:
        if name not in seen:
            deduped.append(name)
            seen.add(name)
    return deduped


def list_archetypes() -> int:
    manifest = load_manifest()
    print(f"archetypes v{manifest.get('version', 'unknown')}\n")
    for row in manifest.get("archetypes", []):
        print(f"- {row['name']}: {row['summary']}")
        print(f"  best for: {row.get('best_for', 'n/a')}")
        print(f"  avoid when: {row.get('avoid_when', 'n/a')}")
        print(f"  weighted object: {row.get('weighted_object', 'n/a')}")
        print(f"  source: {row.get('legacy_source', 'n/a')}")
    return 0


def copy_file(src: Path, dst: Path, force: bool) -> str:
    if dst.exists() and not force:
        return "kept"
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    return "wrote"


def write_bundle(target_dir: Path, selected: list[str], force: bool) -> None:
    css_out = target_dir / "archetypes.css"
    html_out = target_dir / "archetypes.html"

    if css_out.exists() and not force:
        pass
    else:
        parts = [
            "/* Generated by tools/archetype_scaffold.py. */",
            "/* Import this once in your composition CSS. */",
            "",
            (target_dir / "archetype-base.css").read_text(encoding="utf-8"),
        ]
        for name in selected:
            parts.append(f"\n/* {name} */\n")
            parts.append((target_dir / f"{name}.css").read_text(encoding="utf-8"))
        css_out.write_text("\n".join(parts).strip() + "\n", encoding="utf-8")

    if html_out.exists() and not force:
        return

    html_parts = [
        "<!-- Generated by tools/archetype_scaffold.py. -->",
        "<!-- Copy one section per beat, then replace {{placeholders}}. -->",
        "",
    ]
    for name in selected:
        html_parts.append(f"<!-- {name} -->")
        html_parts.append((target_dir / f"{name}.html").read_text(encoding="utf-8"))
        html_parts.append("")
    html_out.write_text("\n".join(html_parts).rstrip() + "\n", encoding="utf-8")


def init_project(project: Path, archetypes: str | None, force: bool) -> int:
    manifest = load_manifest()
    available = known_names(manifest)
    selected = parse_selection(archetypes, available)

    target_dir = project / "_archetypes"
    target_dir.mkdir(parents=True, exist_ok=True)

    print(f"project: {project}")
    print(f"target : {target_dir}\n")

    status = copy_file(LIB / "archetype-base.css", target_dir / "archetype-base.css", force)
    print(f"{status:>5}  archetype-base.css")

    for name in selected:
        for ext in (".html", ".css"):
            src = LIB / f"{name}{ext}"
            if not src.exists():
                raise FileNotFoundError(f"missing archetype file: {src}")
            status = copy_file(src, target_dir / src.name, force)
            print(f"{status:>5}  {src.name}")

    subset = {
        "version": manifest.get("version"),
        "generated_at_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "selected": selected,
        "archetypes": [
            row
            for row in manifest.get("archetypes", [])
            if row.get("name") in set(selected)
        ],
    }
    out_manifest = target_dir / "manifest.json"
    if force or not out_manifest.exists():
        out_manifest.write_text(json.dumps(subset, indent=2), encoding="utf-8")
        print(f"wrote  {out_manifest.name}")
    else:
        print(f" kept  {out_manifest.name}")

    write_bundle(target_dir, selected, force)
    print("wrote  archetypes.css")
    print("wrote  archetypes.html")

    return 0


DEFAULT_SCENES_MANIFEST = {
    "title": "Learn companion video",
    "width": 1920,
    "height": 1080,
    "fps": 30,
    "composition_id": "root",
    "root_background": "#fff8f3",
    "gsap": "assets/vendor/gsap.min.js",
    "fonts": [
        {"family": "Segoe UI", "weight": 400, "src": "fonts/segoeui-regular.woff2"},
        {"family": "Segoe UI Semibold", "weight": 600, "src": "fonts/segoeui-semibold.woff2"},
    ],
    "narration": {"src": "narration.wav"},
    "endcard": {"src": "assets/AI_End_Card.mp4", "duration": 10.667},
    "scenes": [],
}


def _relocate_root_vars(css: str) -> str:
    """A sub-comp scopes CSS to its data-composition-id, so a `:root {}` var block
    would be rewritten to a non-matching descendant selector. Move those vars onto
    #root, which the scoper special-cases as the root itself."""
    return re.sub(r"(^|\n)\s*:root\s*\{", r"\1#root {", css, count=1)


def _strip_clip_timing(fragment: str) -> str:
    """The outer <section> of an archetype fragment carries slot timing
    (data-start/duration/track). In a scene sub-comp the HOST slot owns those, so
    remove them, and drop class="clip" (the scene root is the clip, not the section)."""
    fragment = re.sub(r'\s+data-(?:start|duration|track-index)\s*=\s*"[^"]*"', "", fragment)
    fragment = re.sub(r'class="clip beat', 'class="beat', fragment)
    return fragment


def _indent_css(css: str) -> str:
    return "\n".join(("        " + line if line.strip() else line) for line in css.strip().splitlines())


def load_scenes_manifest(project: Path) -> dict:
    path = project / "scenes.json"
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return json.loads(json.dumps(DEFAULT_SCENES_MANIFEST))


def scaffold_scene(project: Path, scene_id: str, archetype: str, duration: float, force: bool) -> int:
    manifest = load_manifest()
    available = known_names(manifest)
    if archetype not in available:
        raise ValueError(f"unknown archetype '{archetype}'. known: {', '.join(available)}")
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]*", scene_id):
        raise ValueError(f"invalid scene id '{scene_id}' (use letters, digits, dot, dash, underscore)")

    scenes_manifest = load_scenes_manifest(project)
    width = int(scenes_manifest.get("width", 1920))
    height = int(scenes_manifest.get("height", 1080))
    ground = scenes_manifest.get("root_background", "#fff8f3")

    scenes_dir = project / "scenes"
    scenes_dir.mkdir(parents=True, exist_ok=True)
    scene_path = scenes_dir / f"{scene_id}.html"
    if scene_path.exists() and not force:
        raise FileExistsError(f"scene already exists: {scene_path} (use --force)")

    base_css = _relocate_root_vars((LIB / "archetype-base.css").read_text(encoding="utf-8"))
    arche_css = (LIB / f"{archetype}.css").read_text(encoding="utf-8")
    fragment = _strip_clip_timing((LIB / f"{archetype}.html").read_text(encoding="utf-8").strip())
    indented = "\n".join(("        " + line if line else line) for line in fragment.splitlines())

    # No @font-face here: the host declares fonts globally, so scene url() paths never
    # have to resolve — the scene just names the families. gsap in <head> is preview-only
    # (the head is discarded at render; the host provides gsap for the composited doc).
    scene_html = f"""<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <!-- head is preview-only; the runtime clones ONLY the <template> below. -->
    <script src="../assets/vendor/gsap.min.js"></script>
  </head>
  <body>
    <template>
      <style>
        #root {{
          position: absolute;
          inset: 0;
          overflow: hidden;
          container-type: size;
          background: {ground};
          color: var(--hf-ink);
          font-family: "Segoe UI", sans-serif;
        }}

{_indent_css(base_css)}

{_indent_css(arche_css)}
      </style>

      <div id="root" data-composition-id="{scene_id}" data-width="{width}" data-height="{height}">
{indented}
      </div>

      <script>
        window.__timelines = window.__timelines || {{}};
        // Scene-relative, paused, seek-safe. fromTo (not from) replays cleanly on re-seek.
        const tl = gsap.timeline({{ paused: true }});
        tl.fromTo("#root .beat-title", {{ autoAlpha: 0, y: 24 }}, {{ autoAlpha: 1, y: 0, duration: 0.6, ease: "power3.out" }}, 0.1);
        tl.fromTo("#root .chip", {{ autoAlpha: 0, y: 16 }}, {{ autoAlpha: 1, y: 0, duration: 0.5, ease: "power3.out", stagger: 0.08 }}, 0.35);
        window.__timelines["{scene_id}"] = tl;
      </script>
    </template>
  </body>
</html>
"""
    scene_path.write_text(scene_html, encoding="utf-8")

    entry = {"id": scene_id, "src": f"scenes/{scene_id}.html", "duration": round(float(duration), 3), "archetype": archetype}
    scenes = scenes_manifest.setdefault("scenes", [])
    replaced = False
    for i, sc in enumerate(scenes):
        if sc.get("id") == scene_id:
            scenes[i] = entry
            replaced = True
            break
    if not replaced:
        scenes.append(entry)
    (project / "scenes.json").write_text(json.dumps(scenes_manifest, indent=2), encoding="utf-8")

    action = "updated" if replaced else "added"
    print(f"wrote  {scene_path}")
    print(f"{action:>6}  scenes.json entry '{scene_id}' ({archetype}, {entry['duration']}s)")
    print("next   assemble_scenes.py --project <dir>  then  check_subcomps.py --project <dir>")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="cmd", required=True)

    sub.add_parser("list", help="list known archetypes")

    p_init = sub.add_parser("init", help="copy archetypes into a project")
    p_init.add_argument("--project", type=Path, required=True)
    p_init.add_argument(
        "--archetypes",
        help="comma-separated names. Defaults to all archetypes in the manifest.",
    )
    p_init.add_argument("--force", action="store_true", help="overwrite existing files")

    p_scene = sub.add_parser("scene", help="scaffold a per-scene sub-composition file + scenes.json entry")
    p_scene.add_argument("--project", type=Path, required=True)
    p_scene.add_argument("--id", required=True, help="scene id, e.g. 01-opening")
    p_scene.add_argument("--archetype", required=True)
    p_scene.add_argument("--duration", type=float, required=True, help="scene duration in seconds")
    p_scene.add_argument("--force", action="store_true", help="overwrite an existing scene file")

    args = ap.parse_args()

    try:
        if args.cmd == "list":
            return list_archetypes()
        if args.cmd == "init":
            return init_project(args.project, args.archetypes, args.force)
        if args.cmd == "scene":
            return scaffold_scene(args.project, args.id, args.archetype, args.duration, args.force)
    except Exception as exc:  # pragma: no cover
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
