#!/usr/bin/env python3
"""Resolve spoken phrases to real audio times so composition cues stop being guesses.

The pipeline anchored beat STARTS to transcript word times but left every cue
INSIDE a beat as a hand-estimated offset (`B.b6 + 7.4`). Those offsets are
computed from an assumed words-per-second, so they drift the moment the voice
runs faster or slower than the estimate - and per-phrase pace varies far more
than the overall average does. On the first Entra build, 101 of 128 timings
were estimates. That is what "the visuals don't sync with the audio" means.

Usage
-----
  # one-off lookup while authoring
  word_anchors.py transcript.json --find "multifactor authentication"

  # generate anchors.js for a project from an anchors spec
  word_anchors.py transcript.json --spec anchors.json -o anchors.js --lead-in 1.5

The spec is {"anchorName": "spoken phrase", ...}. Phrases are matched as a
contiguous run of transcript tokens, punctuation- and case-insensitive. An
ambiguous phrase is an ERROR, not a silent first-match: append "#2" to pick the
second occurrence explicitly.
"""
import argparse
import json
import pathlib
import re
import sys


def norm(s):
    return re.sub(r"[^\w']", "", s.replace("\u2019", "'")).lower()


def load_words(path):
    data = json.loads(pathlib.Path(path).read_text(encoding="utf-8"))
    return data if isinstance(data, list) else data.get("words", data)


def find_all(words, phrase):
    """Return [(start_index, start_time, end_time)] for every occurrence."""
    keys = [norm(t) for t in phrase.split() if norm(t)]
    if not keys:
        raise ValueError("empty phrase")
    toks = [norm(w["text"]) for w in words]
    hits = []
    for i in range(len(toks) - len(keys) + 1):
        if toks[i:i + len(keys)] == keys:
            hits.append((i, words[i]["start"], words[i + len(keys) - 1]["end"]))
    return hits


def resolve(words, phrase, lead_in):
    occurrence = 1
    m = re.search(r"#(\d+)\s*$", phrase)
    if m:
        occurrence = int(m.group(1))
        phrase = phrase[: m.start()].strip()

    hits = find_all(words, phrase)
    if not hits:
        raise LookupError(f'phrase not found in transcript: "{phrase}"')
    if len(hits) > 1 and not m:
        times = ", ".join(f"{h[1] + lead_in:.3f}s" for h in hits)
        raise LookupError(
            f'ambiguous phrase "{phrase}" - {len(hits)} occurrences at {times}. '
            f'Disambiguate with "{phrase} #1" .. "{phrase} #{len(hits)}".'
        )
    if occurrence > len(hits):
        raise LookupError(f'"{phrase}" has only {len(hits)} occurrence(s), asked for #{occurrence}')

    _, start, end = hits[occurrence - 1]
    return round(start + lead_in, 3), round(end + lead_in, 3)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("transcript", type=pathlib.Path)
    ap.add_argument("--find", help="resolve a single phrase and print its times")
    ap.add_argument("--spec", type=pathlib.Path, help="JSON map of anchorName -> phrase")
    ap.add_argument("-o", "--output", type=pathlib.Path, help="write anchors.js here")
    ap.add_argument("--lead-in", type=float, default=0.0,
                    help="seconds of silence before the VO starts in the composition")
    args = ap.parse_args()

    words = load_words(args.transcript)

    if args.find:
        try:
            start, end = resolve(words, args.find, args.lead_in)
        except LookupError as e:
            print(f"ERROR: {e}", file=sys.stderr)
            return 1
        print(f'"{args.find}"\n  starts {start:.3f}s   ends {end:.3f}s   (lead-in {args.lead_in}s applied)')
        return 0

    if not args.spec:
        ap.error("pass --find or --spec")

    spec = json.loads(args.spec.read_text(encoding="utf-8"))
    spec = {k: v for k, v in spec.items() if not k.startswith("_")}

    anchors, errors = {}, []
    for name, phrase in spec.items():
        try:
            start, end = resolve(words, phrase, args.lead_in)
            anchors[name] = {"start": start, "end": end, "phrase": phrase}
        except LookupError as e:
            errors.append(f"  {name}: {e}")

    for name, a in sorted(anchors.items(), key=lambda kv: kv[1]["start"]):
        print(f'  {a["start"]:8.3f}s  {name:<24} "{a["phrase"]}"')

    if errors:
        print("\nUNRESOLVED:", file=sys.stderr)
        print("\n".join(errors), file=sys.stderr)

    if args.output:
        flat = {k: v["start"] for k, v in anchors.items()}
        ends = {k + "End": v["end"] for k, v in anchors.items()}
        body = json.dumps({**flat, **ends}, indent=2, sort_keys=True)
        args.output.write_text(
            "// GENERATED by tools/word_anchors.py - do not hand-edit.\n"
            "// Every value is a REAL spoken-word time from transcript.json,\n"
            f"// with a {args.lead_in}s lead-in applied. Regenerate after any re-record.\n"
            f"window.__anchors = {body};\n",
            encoding="utf-8",
        )
        print(f"\nwrote {args.output} ({len(anchors)} anchors)")

    if errors:
        return 1
    print(f"\nOK - {len(anchors)}/{len(spec)} anchors resolved")
    return 0


if __name__ == "__main__":
    sys.exit(main())
